exports.SpiritTypes = [
    'Absinthe',
    'Bourbon',
    'Brandy',
    'Cachaça',
    'Gin (Dry)',
    'Gin (New Western)',
    'Liqueur (Almond)',
    'Liqueur (Aperol)',
    'Liqueur (Campari)',
    'Liqueur (Chocolate)',
    'Liqueur (Coffee)',
    'Liqueur (Elderflower)',
    'Liqueur (Hazelnut)',
    'Liqueur (Maraschino)',
    'Liqueur (Melon)',
    'Liqueur (Mint)',
    'Liqueur (Orange)',
    'Mezcal',
    'Rum',
    'Rum (Dark)',
    'Rum (Spiced)',
    'Rum (White)',
    'Sambucca (Black)',
    'Sambucca (White)',
    'Tequila',
    'Vermouth (Red)',
    'Vermouth (White)',
    'Vodka',
    'Whiskey',
    'Whiskey (Rye)',
    'Whiskey (Scotch)',
    'Wine (Fortified)',
    'Wine (Red)',
    'Wine (Sparkling)',
    'Wine (White)',
  ];
